/* tslint:disable */
/* eslint-disable */
/**
 * phoquashApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-07-29 08:18:09UTC
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Configuration } from "./configuration";
import globalAxios, {
  AxiosPromise,
  AxiosInstance,
  AxiosRequestConfig,
} from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "./common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from "./base";

/**
 *
 * @export
 * @interface CreateTravelRecordReturn
 */
export interface CreateTravelRecordReturn {
  /**
   *
   * @type {string}
   * @memberof CreateTravelRecordReturn
   */
  status: string;
  /**
   *
   * @type {string}
   * @memberof CreateTravelRecordReturn
   */
  message: string;
  /**
   *
   * @type {number}
   * @memberof CreateTravelRecordReturn
   */
  travelRecordId?: number;
}
/**
 *
 * @export
 * @interface CreateUserReturn
 */
export interface CreateUserReturn {
  /**
   *
   * @type {string}
   * @memberof CreateUserReturn
   */
  status: string;
  /**
   *
   * @type {string}
   * @memberof CreateUserReturn
   */
  message: string;
  /**
   *
   * @type {number}
   * @memberof CreateUserReturn
   */
  userId?: number;
}
/**
 *
 * @export
 * @interface DeleteTravelRecordReturn
 */
export interface DeleteTravelRecordReturn {
  /**
   *
   * @type {string}
   * @memberof DeleteTravelRecordReturn
   */
  status: string;
  /**
   *
   * @type {string}
   * @memberof DeleteTravelRecordReturn
   */
  message: string;
}
/**
 *
 * @export
 * @interface DeleteTravelReturn
 */
export interface DeleteTravelReturn {
  /**
   *
   * @type {string}
   * @memberof DeleteTravelReturn
   */
  status: string;
  /**
   *
   * @type {string}
   * @memberof DeleteTravelReturn
   */
  message: string;
}
/**
 *
 * @export
 * @interface DeleteUserReturn
 */
export interface DeleteUserReturn {
  /**
   *
   * @type {string}
   * @memberof DeleteUserReturn
   */
  status: string;
  /**
   *
   * @type {string}
   * @memberof DeleteUserReturn
   */
  message: string;
}
/**
 *
 * @export
 * @interface PhotoRequestBody
 */
export interface PhotoRequestBody {
  /**
   *
   * @type {string}
   * @memberof PhotoRequestBody
   */
  description?: string;
  /**
   *
   * @type {number}
   * @memberof PhotoRequestBody
   */
  travelRecordId: number;
  /**
   *
   * @type {string}
   * @memberof PhotoRequestBody
   */
  fileName: string;
  /**
   *
   * @type {string}
   * @memberof PhotoRequestBody
   */
  filePath: string;
  /**
   *
   * @type {string}
   * @memberof PhotoRequestBody
   */
  isFavorite?: string;
}
/**
 *
 * @export
 * @interface PostPhotoReturn
 */
export interface PostPhotoReturn {
  /**
   *
   * @type {string}
   * @memberof PostPhotoReturn
   */
  status: string;
  /**
   *
   * @type {string}
   * @memberof PostPhotoReturn
   */
  message: string;
  /**
   *
   * @type {number}
   * @memberof PostPhotoReturn
   */
  photoId?: number;
}
/**
 *
 * @export
 * @interface PostTravelReturn
 */
export interface PostTravelReturn {
  /**
   *
   * @type {string}
   * @memberof PostTravelReturn
   */
  status: string;
  /**
   *
   * @type {string}
   * @memberof PostTravelReturn
   */
  message: string;
  /**
   *
   * @type {number}
   * @memberof PostTravelReturn
   */
  travelId?: number;
}
/**
 *
 * @export
 * @interface TravelData
 */
export interface TravelData {
  /**
   *
   * @type {string}
   * @memberof TravelData
   */
  status: string;
  /**
   *
   * @type {string}
   * @memberof TravelData
   */
  message: string;
  /**
   *
   * @type {number}
   * @memberof TravelData
   */
  travelId?: number;
  /**
   *
   * @type {number}
   * @memberof TravelData
   */
  userId?: number;
  /**
   *
   * @type {number}
   * @memberof TravelData
   */
  travelRecordId?: number;
}
/**
 *
 * @export
 * @interface TravelDataRequestBody
 */
export interface TravelDataRequestBody {
  /**
   *
   * @type {string}
   * @memberof TravelDataRequestBody
   */
  userName: string;
  /**
   *
   * @type {string}
   * @memberof TravelDataRequestBody
   */
  title: string;
  /**
   *
   * @type {number}
   * @memberof TravelDataRequestBody
   */
  startDate: number;
  /**
   *
   * @type {Interger}
   * @memberof TravelDataRequestBody
   */
  endDate: Interger;
}
/**
 *
 * @export
 * @interface TravelRecordRequestBody
 */
export interface TravelRecordRequestBody {
  /**
   *
   * @type {string}
   * @memberof TravelRecordRequestBody
   */
  userName: string;
  /**
   *
   * @type {string}
   * @memberof TravelRecordRequestBody
   */
  title?: string;
  /**
   *
   * @type {number}
   * @memberof TravelRecordRequestBody
   */
  startDate?: number;
  /**
   *
   * @type {number}
   * @memberof TravelRecordRequestBody
   */
  endDate?: number;
}
/**
 *
 * @export
 * @interface UserData
 */
export interface UserData {
  /**
   *
   * @type {string}
   * @memberof UserData
   */
  status: string;
  /**
   *
   * @type {string}
   * @memberof UserData
   */
  message: string;
  /**
   *
   * @type {number}
   * @memberof UserData
   */
  userId?: number;
  /**
   *
   * @type {string}
   * @memberof UserData
   */
  userName?: string;
}

/**
 * PhotoApi - axios parameter creator
 * @export
 */
export const PhotoApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @summary photoの登録
     * @param {PhotoRequestBody} [photoRequestBody]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createPhoto: async (
      photoRequestBody?: PhotoRequestBody,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/photo`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        photoRequestBody,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * PhotoApi - functional programming interface
 * @export
 */
export const PhotoApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = PhotoApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary photoの登録
     * @param {PhotoRequestBody} [photoRequestBody]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createPhoto(
      photoRequestBody?: PhotoRequestBody,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<Array<PostPhotoReturn>>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createPhoto(
        photoRequestBody,
        options
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
  };
};

/**
 * PhotoApi - factory interface
 * @export
 */
export const PhotoApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = PhotoApiFp(configuration);
  return {
    /**
     *
     * @summary photoの登録
     * @param {PhotoRequestBody} [photoRequestBody]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createPhoto(
      photoRequestBody?: PhotoRequestBody,
      options?: any
    ): AxiosPromise<Array<PostPhotoReturn>> {
      return localVarFp
        .createPhoto(photoRequestBody, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * PhotoApi - object-oriented interface
 * @export
 * @class PhotoApi
 * @extends {BaseAPI}
 */
export class PhotoApi extends BaseAPI {
  /**
   *
   * @summary photoの登録
   * @param {PhotoRequestBody} [photoRequestBody]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PhotoApi
   */
  public createPhoto(
    photoRequestBody?: PhotoRequestBody,
    options?: AxiosRequestConfig
  ) {
    return PhotoApiFp(this.configuration)
      .createPhoto(photoRequestBody, options)
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * TravelApi - axios parameter creator
 * @export
 */
export const TravelApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @summary travelの登録
     * @param {TravelDataRequestBody} [travelDataRequestBody]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createTravel: async (
      travelDataRequestBody?: TravelDataRequestBody,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/travel`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        travelDataRequestBody,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary travelの削除
     * @param {TravelDataRequestBody} [travelDataRequestBody]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteTravel: async (
      travelDataRequestBody?: TravelDataRequestBody,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/travel`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        travelDataRequestBody,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary travelIdを元にしたtravelの削除
     * @param {string} travelId Generated path parameter for travelId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteTravelById: async (
      travelId: string,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'travelId' is not null or undefined
      assertParamExists("deleteTravelById", "travelId", travelId);
      const localVarPath = `/travel/{travelId}`.replace(
        `{${"travelId"}}`,
        encodeURIComponent(String(travelId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary travelIdを元にしたtravelの取得
     * @param {string} travelId Generated path parameter for travelId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTravelById: async (
      travelId: string,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'travelId' is not null or undefined
      assertParamExists("getTravelById", "travelId", travelId);
      const localVarPath = `/travel/{travelId}`.replace(
        `{${"travelId"}}`,
        encodeURIComponent(String(travelId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * TravelApi - functional programming interface
 * @export
 */
export const TravelApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = TravelApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary travelの登録
     * @param {TravelDataRequestBody} [travelDataRequestBody]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createTravel(
      travelDataRequestBody?: TravelDataRequestBody,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<Array<PostTravelReturn>>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createTravel(
        travelDataRequestBody,
        options
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @summary travelの削除
     * @param {TravelDataRequestBody} [travelDataRequestBody]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteTravel(
      travelDataRequestBody?: TravelDataRequestBody,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<Array<DeleteTravelReturn>>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTravel(
        travelDataRequestBody,
        options
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @summary travelIdを元にしたtravelの削除
     * @param {string} travelId Generated path parameter for travelId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteTravelById(
      travelId: string,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<Array<DeleteTravelReturn>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.deleteTravelById(travelId, options);
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @summary travelIdを元にしたtravelの取得
     * @param {string} travelId Generated path parameter for travelId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getTravelById(
      travelId: string,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<Array<TravelData>>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getTravelById(
        travelId,
        options
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
  };
};

/**
 * TravelApi - factory interface
 * @export
 */
export const TravelApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = TravelApiFp(configuration);
  return {
    /**
     *
     * @summary travelの登録
     * @param {TravelDataRequestBody} [travelDataRequestBody]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createTravel(
      travelDataRequestBody?: TravelDataRequestBody,
      options?: any
    ): AxiosPromise<Array<PostTravelReturn>> {
      return localVarFp
        .createTravel(travelDataRequestBody, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary travelの削除
     * @param {TravelDataRequestBody} [travelDataRequestBody]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteTravel(
      travelDataRequestBody?: TravelDataRequestBody,
      options?: any
    ): AxiosPromise<Array<DeleteTravelReturn>> {
      return localVarFp
        .deleteTravel(travelDataRequestBody, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary travelIdを元にしたtravelの削除
     * @param {string} travelId Generated path parameter for travelId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteTravelById(
      travelId: string,
      options?: any
    ): AxiosPromise<Array<DeleteTravelReturn>> {
      return localVarFp
        .deleteTravelById(travelId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary travelIdを元にしたtravelの取得
     * @param {string} travelId Generated path parameter for travelId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTravelById(
      travelId: string,
      options?: any
    ): AxiosPromise<Array<TravelData>> {
      return localVarFp
        .getTravelById(travelId, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * TravelApi - object-oriented interface
 * @export
 * @class TravelApi
 * @extends {BaseAPI}
 */
export class TravelApi extends BaseAPI {
  /**
   *
   * @summary travelの登録
   * @param {TravelDataRequestBody} [travelDataRequestBody]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TravelApi
   */
  public createTravel(
    travelDataRequestBody?: TravelDataRequestBody,
    options?: AxiosRequestConfig
  ) {
    return TravelApiFp(this.configuration)
      .createTravel(travelDataRequestBody, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary travelの削除
   * @param {TravelDataRequestBody} [travelDataRequestBody]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TravelApi
   */
  public deleteTravel(
    travelDataRequestBody?: TravelDataRequestBody,
    options?: AxiosRequestConfig
  ) {
    return TravelApiFp(this.configuration)
      .deleteTravel(travelDataRequestBody, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary travelIdを元にしたtravelの削除
   * @param {string} travelId Generated path parameter for travelId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TravelApi
   */
  public deleteTravelById(travelId: string, options?: AxiosRequestConfig) {
    return TravelApiFp(this.configuration)
      .deleteTravelById(travelId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary travelIdを元にしたtravelの取得
   * @param {string} travelId Generated path parameter for travelId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TravelApi
   */
  public getTravelById(travelId: string, options?: AxiosRequestConfig) {
    return TravelApiFp(this.configuration)
      .getTravelById(travelId, options)
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * TravelRecordApi - axios parameter creator
 * @export
 */
export const TravelRecordApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @summary travelRecordの登録
     * @param {TravelRecordRequestBody} [travelRecordRequestBody]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createTravelRecord: async (
      travelRecordRequestBody?: TravelRecordRequestBody,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/travelRecord`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        travelRecordRequestBody,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary travelRecordの削除
     * @param {TravelDataRequestBody} [travelDataRequestBody]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteTravelRecord: async (
      travelDataRequestBody?: TravelDataRequestBody,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/travelRecord`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        travelDataRequestBody,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary travelRecordIdを元にしたTravelRecordの削除
     * @param {string} travelRecordId Generated path parameter for travelRecordId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteTravelRecordById: async (
      travelRecordId: string,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'travelRecordId' is not null or undefined
      assertParamExists(
        "deleteTravelRecordById",
        "travelRecordId",
        travelRecordId
      );
      const localVarPath = `/travelRecord/{travelRecordId}`.replace(
        `{${"travelRecordId"}}`,
        encodeURIComponent(String(travelRecordId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * TravelRecordApi - functional programming interface
 * @export
 */
export const TravelRecordApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    TravelRecordApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary travelRecordの登録
     * @param {TravelRecordRequestBody} [travelRecordRequestBody]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createTravelRecord(
      travelRecordRequestBody?: TravelRecordRequestBody,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<Array<CreateTravelRecordReturn>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.createTravelRecord(
          travelRecordRequestBody,
          options
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @summary travelRecordの削除
     * @param {TravelDataRequestBody} [travelDataRequestBody]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteTravelRecord(
      travelDataRequestBody?: TravelDataRequestBody,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<Array<DeleteTravelRecordReturn>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.deleteTravelRecord(
          travelDataRequestBody,
          options
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @summary travelRecordIdを元にしたTravelRecordの削除
     * @param {string} travelRecordId Generated path parameter for travelRecordId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteTravelRecordById(
      travelRecordId: string,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<Array<DeleteTravelRecordReturn>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.deleteTravelRecordById(
          travelRecordId,
          options
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
  };
};

/**
 * TravelRecordApi - factory interface
 * @export
 */
export const TravelRecordApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = TravelRecordApiFp(configuration);
  return {
    /**
     *
     * @summary travelRecordの登録
     * @param {TravelRecordRequestBody} [travelRecordRequestBody]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createTravelRecord(
      travelRecordRequestBody?: TravelRecordRequestBody,
      options?: any
    ): AxiosPromise<Array<CreateTravelRecordReturn>> {
      return localVarFp
        .createTravelRecord(travelRecordRequestBody, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary travelRecordの削除
     * @param {TravelDataRequestBody} [travelDataRequestBody]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteTravelRecord(
      travelDataRequestBody?: TravelDataRequestBody,
      options?: any
    ): AxiosPromise<Array<DeleteTravelRecordReturn>> {
      return localVarFp
        .deleteTravelRecord(travelDataRequestBody, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary travelRecordIdを元にしたTravelRecordの削除
     * @param {string} travelRecordId Generated path parameter for travelRecordId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteTravelRecordById(
      travelRecordId: string,
      options?: any
    ): AxiosPromise<Array<DeleteTravelRecordReturn>> {
      return localVarFp
        .deleteTravelRecordById(travelRecordId, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * TravelRecordApi - object-oriented interface
 * @export
 * @class TravelRecordApi
 * @extends {BaseAPI}
 */
export class TravelRecordApi extends BaseAPI {
  /**
   *
   * @summary travelRecordの登録
   * @param {TravelRecordRequestBody} [travelRecordRequestBody]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TravelRecordApi
   */
  public createTravelRecord(
    travelRecordRequestBody?: TravelRecordRequestBody,
    options?: AxiosRequestConfig
  ) {
    return TravelRecordApiFp(this.configuration)
      .createTravelRecord(travelRecordRequestBody, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary travelRecordの削除
   * @param {TravelDataRequestBody} [travelDataRequestBody]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TravelRecordApi
   */
  public deleteTravelRecord(
    travelDataRequestBody?: TravelDataRequestBody,
    options?: AxiosRequestConfig
  ) {
    return TravelRecordApiFp(this.configuration)
      .deleteTravelRecord(travelDataRequestBody, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary travelRecordIdを元にしたTravelRecordの削除
   * @param {string} travelRecordId Generated path parameter for travelRecordId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TravelRecordApi
   */
  public deleteTravelRecordById(
    travelRecordId: string,
    options?: AxiosRequestConfig
  ) {
    return TravelRecordApiFp(this.configuration)
      .deleteTravelRecordById(travelRecordId, options)
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @summary userの登録
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createUser: async (
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/user`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary userの削除
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteUser: async (
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/user`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary userの削除
     * @param {string} userId Generated path parameter for userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteUserById: async (
      userId: string,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'userId' is not null or undefined
      assertParamExists("deleteUserById", "userId", userId);
      const localVarPath = `/user/{userId}`.replace(
        `{${"userId"}}`,
        encodeURIComponent(String(userId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary userIdを元にしたuserの取得
     * @param {string} userId Generated path parameter for userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getUserById: async (
      userId: string,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'userId' is not null or undefined
      assertParamExists("getUserById", "userId", userId);
      const localVarPath = `/user/{userId}`.replace(
        `{${"userId"}}`,
        encodeURIComponent(String(userId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary userの登録
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createUser(
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<Array<CreateUserReturn>>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createUser(
        options
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @summary userの削除
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteUser(
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<Array<DeleteUserReturn>>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteUser(
        options
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @summary userの削除
     * @param {string} userId Generated path parameter for userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteUserById(
      userId: string,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<Array<DeleteUserReturn>>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteUserById(
        userId,
        options
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @summary userIdを元にしたuserの取得
     * @param {string} userId Generated path parameter for userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getUserById(
      userId: string,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<Array<UserData>>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getUserById(
        userId,
        options
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
  };
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = UserApiFp(configuration);
  return {
    /**
     *
     * @summary userの登録
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createUser(options?: any): AxiosPromise<Array<CreateUserReturn>> {
      return localVarFp
        .createUser(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary userの削除
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteUser(options?: any): AxiosPromise<Array<DeleteUserReturn>> {
      return localVarFp
        .deleteUser(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary userの削除
     * @param {string} userId Generated path parameter for userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteUserById(
      userId: string,
      options?: any
    ): AxiosPromise<Array<DeleteUserReturn>> {
      return localVarFp
        .deleteUserById(userId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary userIdを元にしたuserの取得
     * @param {string} userId Generated path parameter for userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getUserById(userId: string, options?: any): AxiosPromise<Array<UserData>> {
      return localVarFp
        .getUserById(userId, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
  /**
   *
   * @summary userの登録
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UserApi
   */
  public createUser(options?: AxiosRequestConfig) {
    return UserApiFp(this.configuration)
      .createUser(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary userの削除
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UserApi
   */
  public deleteUser(options?: AxiosRequestConfig) {
    return UserApiFp(this.configuration)
      .deleteUser(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary userの削除
   * @param {string} userId Generated path parameter for userId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UserApi
   */
  public deleteUserById(userId: string, options?: AxiosRequestConfig) {
    return UserApiFp(this.configuration)
      .deleteUserById(userId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary userIdを元にしたuserの取得
   * @param {string} userId Generated path parameter for userId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UserApi
   */
  public getUserById(userId: string, options?: AxiosRequestConfig) {
    return UserApiFp(this.configuration)
      .getUserById(userId, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
